Nucleotides = ["A", "C", "G", "T"]

def validateSeq(dna_seq):
    tmpseq = dna_seq.upper()
    
    for nuc in tmpseq:
        if nuc not in Nucleotides:
            return False
    return True

def RNAtranscription(seq):
    RNA = ""
    if(validateSeq(seq)):
        for nuc in seq:
            if (nuc == 'T'):
                nuc = 'U'
            RNA = RNA + nuc
        return RNA
            
    else:
        raise("String is not a DNA! Please verify if it's an DNA [1]")

DNA = "ATATGCCGCCTTCAGTACTACTCTTTCGTGGGCATTCTGATGTAAGAACAGCATAAGTAAATCAGGACTATCCACGCATCTCTCTCACTATCTATAGGCTGGGCACGTTGCATTTTTTTACCTTTCGGAAGATAATAGAAAACGCTCAGGCACATATAAGAATTTATATCCCTCTAGGACCGTACCAGCACTCGTTCTGCCCCTCGGACAACAGGCAGGCCGCCTTCATCCCGCCCGGATCCGCTATGAGAGGACAGGCATGATTTACACACAATTACCGCGGTTTCAGAGTCTGGGATGAGCGCCGAGAAAATTATATAATACAATGATAACATCAGTCGCAGCTTCATTTACCTGGCGATATATGGGGTAACGCCTTCTGGGCTGCATCAGCTGCGCGATATAAGACAGGGAGCCAACGATTATAACTTGCTAGGAAGGCGGTCTAGAGGCAAGATCCGAATTTACACTCGAGTACTCGCACGCCTTCTCTCTCGTCACATATCCTACCTGTCGGCAATAGTGATTTGCATTGCTAGGATGATCCGGAGGCGACAGAATTCATGACTATCACCACTCGCAAACTGCGCACTTTTCCGCAGTGGAGAGTTCGAGCGACTAACCGATCGCAGCCCGCGAAGTTAGGACGGACCTTTCCGTTCTGCCAACTTGTCTTCGTCTACCAGGATCCGTATTCAGGTGCGTTGTATGAGGTCAATTTTCATTAAGGGCCGACTCCCAATCATCACCACCAGCGGACCGGCCAAACACTCTCAATATGGAACCTATGTCGTTGTAAGGTCGCCAAATACGGACATGTCGACATATTCGTTGATGGTATGATTTCCGCGTTGGCCGATGCATTACGGGTGGTATGTAACGCGTTCGCAGTCCTCCCCACGGGAAAAGCCAAACAGCGGAATTGCCCTAAAAAAGTGCAGCGTCAGCCCTGTAAGAAGTCCAGGTTGTGGCAAGCTATCAGGCATCATAA"
print(RNAtranscription(DNA))